title: Best Magisk Module
email: null@gmail.com
description: "National University of Bangladesh CollegeWise Result"
baseurl: "/"
url: "https://collegewiseresult.github.io/"
twitter_username: NUBD
github_username:  NUBD
author: NUBD


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
